# Generated by Django 3.0.5 on 2020-05-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
